import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Cpu, HardDrive, Users, Wifi, Plus, RefreshCw, Trash2, Power} from 'lucide-react';
import './style.css';
const API='/api';
function fmt(b){if(!b)return '0 B'; const u=['B','KB','MB','GB','TB']; let i=0,n=b; while(n>=1024&&i<u.length-1){n/=1024;i++} return n.toFixed(1)+' '+u[i]}
function App(){const [token,setToken]=useState(localStorage.token||''); const [login,setLogin]=useState({username:'',password:''}); const [tab,setTab]=useState('overview'); const [ov,setOv]=useState(null); const [users,setUsers]=useState([]); const [form,setForm]=useState({name:'',traffic_limit_gb:10,expires_days:30,sponsor_tag:''}); const [err,setErr]=useState('');
const auth={Authorization:'Bearer '+token,'Content-Type':'application/json'};
async function api(path,opt={}){let r=await fetch(API+path,{...opt,headers:{...auth,...(opt.headers||{})}}); if(!r.ok) throw new Error((await r.text()).slice(0,200)); return r.json()}
async function load(){ if(!token) return; try{setOv(await api('/overview')); setUsers(await api('/users'));}catch(e){setErr(e.message)} }
useEffect(()=>{load(); const t=setInterval(load,10000); return()=>clearInterval(t)},[token]);
async function doLogin(e){e.preventDefault(); setErr(''); let r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(login)}); if(!r.ok){setErr('ورود ناموفق'); return} let j=await r.json(); localStorage.token=j.access_token; setToken(j.access_token)}
async function createUser(e){e.preventDefault(); setErr(''); try{await api('/users',{method:'POST',body:JSON.stringify({...form,traffic_limit_gb:Number(form.traffic_limit_gb),expires_days:Number(form.expires_days)})}); setForm({...form,name:''}); load()}catch(e){setErr(e.message)}}
async function action(path,method='POST'){try{await api(path,{method}); load()}catch(e){setErr(e.message)}}
if(!token) return <div className="login"><form onSubmit={doLogin}><h1>DELTA PROXY PANEL</h1><input placeholder="Username" value={login.username} onChange={e=>setLogin({...login,username:e.target.value})}/><input placeholder="Password" type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/><button>ورود</button>{err&&<p className="err">{err}</p>}</form></div>
return <div className="app" dir="rtl"><aside><h2>DELTA PROXY PANEL</h2><button className={tab==='overview'?'on':''} onClick={()=>setTab('overview')}>Overview</button><button className={tab==='users'?'on':''} onClick={()=>setTab('users')}>Users</button><button onClick={()=>{localStorage.removeItem('token');setToken('')}}>خروج</button></aside><main><header><h1>{tab==='overview'?'نمای کلی سرور':'مدیریت کاربران'}</h1><button onClick={load}><RefreshCw size={16}/> بروزرسانی</button></header>{err&&<div className="err box">{err}</div>}{tab==='overview'&&ov&&<section className="grid"><Card icon={<Cpu/>} t="CPU" v={`${ov.cpu_percent}% / ${ov.cpu_count} cores`}/><Card icon={<HardDrive/>} t="RAM" v={`${fmt(ov.ram_used)} / ${fmt(ov.ram_total)}`}/><Card icon={<HardDrive/>} t="Disk" v={`${fmt(ov.disk_used)} / ${fmt(ov.disk_total)}`}/><Card icon={<Wifi/>} t="Network" v={`↓ ${fmt(ov.net_recv)} / ↑ ${fmt(ov.net_sent)}`}/><Card icon={<Users/>} t="Users" v={`${ov.users_active} فعال از ${ov.users_total}`}/><Card icon={<Wifi/>} t="Host" v={ov.public_host || 'از env تنظیم نشده'}/><Card icon={<Wifi/>} t="Proxy Port" v={String(ov.proxy_port || ov.port_range || '')}/><Card icon={<Wifi/>} t="Proxy Traffic" v={fmt(ov.shared_proxy_traffic_bytes)}/></section>}{tab==='users'&&<section><form className="create" onSubmit={createUser}><input placeholder="نام کاربر" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="حجم GB، صفر یعنی نامحدود" value={form.traffic_limit_gb} onChange={e=>setForm({...form,traffic_limit_gb:e.target.value})}/><input placeholder="روز اعتبار" value={form.expires_days} onChange={e=>setForm({...form,expires_days:e.target.value})}/><input placeholder="Sponsor tag اختیاری" value={form.sponsor_tag} onChange={e=>setForm({...form,sponsor_tag:e.target.value})}/><button><Plus size={16}/> ساخت</button></form><div className="table">{users.map(u=><div className="row" key={u.id}><div><b>{u.name}</b><small>Port: {u.port} | {u.status} | expire: {u.expires_at?.slice(0,10)||'∞'}</small><code>{u.link}</code><small>Traffic limit: {u.traffic_limit_bytes?fmt(u.traffic_limit_bytes):'∞'} | یک‌پورت: شمارش دقیق حجم هر سکرت پشتیبانی نمی‌شود</small></div><div className="actions"><button onClick={()=>navigator.clipboard.writeText(u.link)}>کپی لینک</button><button onClick={()=>action(`/users/${u.id}/reset-traffic`)}>ریست حجم</button><button onClick={()=>action(`/users/${u.id}/restart`)}>Restart</button><button onClick={()=>api(`/users/${u.id}`,{method:'PATCH',body:JSON.stringify({active:!u.active})}).then(load).catch(e=>setErr(e.message))}><Power size={15}/> {u.active?'خاموش':'روشن'}</button><button onClick={()=>action(`/users/${u.id}`, 'DELETE')}><Trash2 size={15}/></button></div></div>)}</div></section>}</main></div>}
function Card({icon,t,v}){return <div className="card">{icon}<span>{t}</span><b>{v}</b></div>}
createRoot(document.getElementById('root')).render(<App/>);
